name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - dev
      - staging
      - prod

jobs:
  terraform:
    name: Apply Terraform in ${{ github.ref }}
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.11

    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/${{ github.ref }}

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: ./environments/${{ github.ref }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/dev' || github.ref == 'refs/heads/staging' || github.ref == 'refs/heads/prod'
      run: terraform apply -var-file="terraform.tfvars" -auto-approve
      working-directory: ./environments/${{ github.ref }}
