name: Terraform CI/CD

on:
  push:
    branches:
      - dev
      - staging
      - prod
  workflow_dispatch:

jobs:
  terraform_apply:
    name: Apply Terraform in ${{ github.ref_name }} branch
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.11

    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/${{ github.ref_name }}

    - name: Terraform Plan
      run: terraform plan -var-file="terraform.tfvars"
      working-directory: ./environments/${{ github.ref_name }}

    - name: Terraform Apply
      if: github.ref_name == 'dev' || github.ref_name == 'staging' || github.ref_name == 'prod'
      run: terraform apply -var-file="terraform.tfvars" -auto-approve
      working-directory: ./environments/${{ github.ref_name }}

  terraform_destroy:
    name: Destroy Terraform in ${{ github.ref_name }} branch
    runs-on: ubuntu-latest
    needs: terraform_apply # Pode remover esta linha caso queira que o destroy seja executado independentemente do apply

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.11

    - name: Terraform Init
      run: terraform init
      working-directory: ./environments/${{ github.ref_name }}

    - name: Terraform Plan for Destroy
      run: terraform plan -destroy -var-file="terraform.tfvars"
      working-directory: ./environments/${{ github.ref_name }}

    - name: Terraform Destroy
      run: terraform destroy -var-file="terraform.tfvars" -auto-approve
      working-directory: ./environments/${{ github.ref_name }}
